### ISSUE TITLE
Баги: Главная страница

### ISSUE THREAD

**Issue by alexdany657** [m20-sch57/thehat#10]
Надо пофиксить баги:

- TypeError: navigator.clipboard.readText is not a function

- проблема с getRoomInfo при пустом ключе (надо запретить "плохие ключи")

- проблема при отрисовки с пустым именем (надо запретить пустое имя)

**Comment by gtivansan** [comment]
Надо всё-таки отдельные issues делать.

**Comment by gtivansan** [comment]
1-й пункт тут #11 
2-й пункт тут #12 
3-й пункт тут #13
